# install with conda env create -f environment.yml
name: vdash
channels:
  - conda-forge
dependencies:
  - dash=2.18.2
  - dash-bootstrap-components=1.7.1
  - pandas=2.2.1
  - pip=25.0.1
  - plotly=6.0.0
  - python=3.11
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - altair=5.5.0
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - joblib=1.4.2
  - pyarrow=19.0.1
  - vegafusion=2.0.1
  - pip:
      - dash-vega-components
      - kagglehub
      - vl-convert-python==1.7.0